namespace WingsAPI.Data.Families;

public enum FamilyUpgradeType
{
    INCREASE_ATTACK_DEFENSE = 0,
    INCREASE_FOOD_SNACK_REGEN = 1,
    DECREASE_SHIP_TP_COST = 2,
    INCREASE_POTION_REGEN = 3,
    INCREASE_FAMILY_WAREHOUSE = 4,
    INCREASE_FAMILY_MEMBERS_LIMIT = 5,


    FIRE_RESISTANCE,
    WATER_RESISTANCE,
    DARK_RESISTANCE,
    LIGHT_RESISTANCE
}