using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using PhoenixLib.DAL;

namespace WingsEmu.DTOs.Quests;

public class TutorialDto : IIntDto
{
    public int Data { get; set; }
    public int ScriptId { get; set; }
    public int ScriptIndex { get; set; }
    public TutorialActionType Type { get; set; }

    /// <summary>
    ///     Generated by parser
    /// </summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }
}