namespace WingsEmu.Game._enum;

public enum MorphIdType
{
    Pyjama = 1,
    Warrior = 2,
    Ninja = 3,
    Ranger = 4,
    Assassin = 5,
    RedMagician = 6,
    HolyMage = 7,
    Chicken = 8,
    Jajamaru = 9,
    Crusader = 10,
    Berserker = 11,
    Destroyer = 12,
    WildKeeper = 13,
    BlueMagician = 14,
    DarkGunner = 15,
    Pirate = 16,
    Gladiator = 17,
    FireCannoneer = 18,
    Volcano = 19,
    BattleMonk = 20,
    Scout = 21,
    TideLord = 22,
    DeathReaper = 23,
    DemonHunter = 24,
    Seer = 25,
    Renegade = 26,
    AvengingAngel = 27,
    Archmage = 28,
    DraconicFist = 29,
    MysticArts = 31,
    WeddingCostume = 32,
    MasterWolf = 33,
    DemonWarrior = 34
}