namespace WingsEmu.Game._enum;

public enum ReputationType : byte
{
    BEGINNER_1 = 1,
    BEGINNER_2 = 2,
    BEGINNER_3 = 3,
    GREEN_TRAINEE = 4,
    BLUE_TRAINEE = 5,
    RED_TRAINEE = 6,

    GREEN_EXPERIENCED = 7,
    BLUE_EXPERIENCED = 8,
    RED_EXPERIENCED = 9,

    GREEN_BATTLE_SOLDIER = 10,
    BLUE_BATTLE_SOLDIER = 11,
    RED_BATTLE_SOLDIER = 12,

    GREEN_EXPERT = 13,
    BLUE_EXPERT = 14,
    RED_EXPERT = 15,

    GREEN_LEADER = 16,
    BLUE_LEADER = 17,
    RED_LEADER = 18,

    GREEN_MASTER = 19,
    BLUE_MASTER = 20,
    RED_MASTER = 21,

    GREEN_NOS = 22,
    BLUE_NOS = 23,
    RED_NOS = 24,

    GREEN_ELITE = 25,
    BLUE_ELITE = 26,
    RED_ELITE = 27,

    SECOND_LEGEND = 28,
    FIRST_LEGEND = 29,

    ANCIENT_HERO = 30,
    MYSTERIOUS_HERO = 31,
    LEGENDARY_HERO = 32
}