namespace WingsEmu.Game._enum;

public enum SoundType : short
{
    CLICK_BUTTON = 1,
    CAMERA_SHOT = 2,
    ADVENTURER_DEATH = 3,
    WALKING = 5,
    WALKING_2 = 6,
    TS_DANGER = 7,
    WALKING_3 = 8,
    LEVEL_UP = 9,
    PICK_UP_ITEM = 10,
    TS_ENDING_TIME = 12,
    ATTACK = 13,
    ITEM_MOVING = 16,
    JOB_LEVEL_UP = 23,
    TARGET = 26,
    SECOND_CHANCE = 334,
    WARNING = 928,
    NO_MANA = 1323,
    CRAFTING_SUCCESS = 1324,
    BUY_SKILL = 1326,
    CRAFTING_FAILED = 1332,
    TAUNT_SKILL = 1691,
    MEDITATION_FIRST = 1824,
    MEDITATION_SECOND = 1825,
    MEDITATION_THIRD = 1826
}